<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SPMUMLAP-043" failures="0" tests="9" name="Core.AddAgency.CoreAddAgency_TestClass" time="27.629" errors="1" timestamp="2025-05-08T17:08:23 IST" skipped="8">
  <testcase classname="Core.AddAgency.CoreAddAgency_TestClass" name="SetUp" time="27.629">
    <error message="Cannot invoke &quot;java.sql.Connection.prepareStatement(String)&quot; because &quot;con&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.sql.Connection.prepareStatement(String)" because "con" is null
at com.BasePackage.DBUtils.fetchSingleValueFromDB(DBUtils.java:22)
at com.BasePackage.Login_Class.CoreLogin(Login_Class.java:59)
at Core.AddAgency.CoreAddAgency_TestClass.SetUp(CoreAddAgency_TestClass.java:76)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:358)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- SetUp -->
  <testcase classname="Core.AddAgency.CoreAddAgency_TestClass" name="Login_to_CoreWithHO_User" time="0.000">
    <skipped/>
  </testcase> <!-- Login_to_CoreWithHO_User -->
  <testcase classname="Core.AddAgency.CoreAddAgency_TestClass" name="Validate_AddAgency_Page" time="0.000">
    <skipped/>
  </testcase> <!-- Validate_AddAgency_Page -->
  <testcase classname="Core.AddAgency.CoreAddAgency_TestClass" name="Validate_Invalid_PAN_WarningMessage" time="0.000">
    <skipped/>
  </testcase> <!-- Validate_Invalid_PAN_WarningMessage -->
  <testcase classname="Core.AddAgency.CoreAddAgency_TestClass" name="Validate_Valid_PAN" time="0.000">
    <skipped/>
  </testcase> <!-- Validate_Valid_PAN -->
  <testcase classname="Core.AddAgency.CoreAddAgency_TestClass" name="Validate_InvalidGST" time="0.000">
    <skipped/>
  </testcase> <!-- Validate_InvalidGST -->
  <testcase classname="Core.AddAgency.CoreAddAgency_TestClass" name="Validate_validGST" time="0.000">
    <skipped/>
  </testcase> <!-- Validate_validGST -->
  <testcase classname="Core.AddAgency.CoreAddAgency_TestClass" name="Validate_InvalidCollectionName" time="0.000">
    <skipped/>
  </testcase> <!-- Validate_InvalidCollectionName -->
  <testcase classname="Core.AddAgency.CoreAddAgency_TestClass" name="Validate_validCollectionAgencyName" time="0.000">
    <skipped/>
  </testcase> <!-- Validate_validCollectionAgencyName -->
</testsuite> <!-- Core.AddAgency.CoreAddAgency_TestClass -->
